### ISSUE TITLE
2核8G玩了五六个小时后内存满了

### ISSUE THREAD

**Issue by codexu** [2lifetop/Pal-Server-Install#1]
请问设置虚拟内存有用吗？
<img width="639" alt="image" src="https://github.com/2lifetop/Pal-Server-Install/assets/15899990/a41ca7c8-5b45-491d-8631-5800641a07f4">
请问我选择5，这个值应该怎么填，我乱填了一个2，结果改不了了，请问如何运行脚本删除swap后重新设置

**Comment by 2lifetop** [comment]
你这个是服务器已经有了，可以尝试7选项，重启服务端，看看能否减轻内存占用。可以说明一下有多少人在玩。人越多需要的内存就越多，你可以按每个人占用1-3GB内存来计算能同时承载多少人游玩。然后服务器本身占用也得2GB。所以还是建议服务器上16G内存

**Comment by codexu** [comment]
感谢大佬，俩人玩，现在内存高了重启一下就好了
