### ISSUE TITLE
内存泄露监控脚本

### ISSUE THREAD

**Issue by LittleFi987** [2lifetop/Pal-Server-Install#11]
建议写一个监控服务器内存的脚本，达到一定阈值后自动重启，还能抢救一下。
先🐴一下，等有空写一个，或者好心人直接提供一个

**Comment by FlyingRadish** [comment]
@LittleFi987 试试这个https://github.com/FlyingRadish/pal-server-helper

**Comment by LittleFi987** [comment]
> @LittleFi987 试试这个https://github.com/FlyingRadish/pal-server-helper

感觉可以提个pr，直接集成到这个脚本里吧

**Comment by FlyingRadish** [comment]
> > @LittleFi987 试试这个https://github.com/FlyingRadish/pal-server-helper
> 
> 感觉可以提个pr，直接集成到这个脚本里吧

我看行，不过我不太熟悉shell脚本编写....大概思路是有

**Comment by FlyingRadish** [comment]
> > @LittleFi987 试试这个https://github.com/FlyingRadish/pal-server-helper
> 
> 感觉可以提个pr，直接集成到这个脚本里吧

我看行，不过我不太会写shell脚本...

我目前想到的大概思路是：
1. 下载打包好的压缩包
2. 初始化helper配置文件
3. 创建systemd服务并启动

**Comment by LittleFi987** [comment]
> > > @LittleFi987 试试这个https://github.com/FlyingRadish/pal-server-helper
> > 
> > 
> > 感觉可以提个pr，直接集成到这个脚本里吧
> 
> 我看行，不过我不太会写shell脚本...
> 
> 我目前想到的大概思路是：
> 
> 1. 下载打包好的压缩包
> 2. 初始化helper配置文件
> 3. 创建systemd服务并启动

差不太多，还有就是内存参数阈值修改集成到脚本里，等有空的话，我可以整下

**Comment by hapeman0314** [comment]
因为是用docker运行的服务器所以只需要在153行 运行docker 的命令 添加参数 `--m=7g --restart=always` 就可以实现内存占用达到7G的时候自动重启了

**Comment by 2lifetop** [comment]
已增加
