### ISSUE TITLE
更新补丁报错

### ISSUE THREAD

**Issue by YIDA0580** [2lifetop/Pal-Server-Install#14]
请输入数字 [1-15]:12
新的补丁版本可用，版本为 1.3.3。是否要更新至最新版补丁? (y/n) y
正在下载新的补丁版本...
--2024-01-26 12:20:02--  https://mirror.ghproxy.com/https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix/releases/download/1.3.0-Update-3-Beta/PalServer-Linux-Test-Patch-Update-3-Beta
Resolving mirror.ghproxy.com (mirror.ghproxy.com)... 141.147.152.25
Connecting to mirror.ghproxy.com (mirror.ghproxy.com)|141.147.152.25|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 189756648 (181M) [application/octet-stream]
Saving to: ‘PalServer-Linux-Test’

PalServer-Linux-Test       100%[=======================================>] 180.97M   485KB/s    in 10m 22s 

2024-01-26 12:30:28 (298 KB/s) - ‘PalServer-Linux-Test’ saved [189756648/189756648]

Successfully copied 393kB to steamcmd:/home/steam/Steam/steamapps/common/PalServer/Pal/Binaries/Linux/PalServer-Linux-Test
Error response from daemon: Could not find the file /home/steam/Steam/steamapps/common/PalServer/Pal/Binaries/Linux in container steamcmd
$1 失败

**Comment by 2lifetop** [comment]
本脚本目前暂不支持ARM服务器。
更新前请先确保steamcmd容器正在运行。可以通过脚本查看服务端状态

**Comment by YIDA0580** [comment]
> 本脚本目前暂不支持ARM服务器。 更新前请先确保steamcmd容器正在运行。可以通过脚本查看服务端状态

用的是运行在exsi上的ubuntu，portainer中显示容器正在运行

**Comment by 2lifetop** [comment]
怀疑你的硬盘空间不足

**Comment by YIDA0580** [comment]
> 怀疑你的硬盘空间不足

似乎是安装docker时没有完整安装
