### ISSUE TITLE
几个疑问

### ISSUE THREAD

**Issue by et5494** [2lifetop/Pal-Server-Install#16]
1.你的更新日志对应的脚本版本号是多少？
2.现在内存刷刷的上去，2个人比较肝，现在已经20g+的内存的。发现一个FIX https://www.xuehaiwu.com/palworld-server/ ，这个能替换进去吗？（没有测试过，。。）

**Comment by 2lifetop** [comment]
fix什么对什么，更新日志对应脚本号后续会同步加上。你可以先手动重启缓解内存压力，目前定时重启还有个小bug下个版本修复
