### ISSUE TITLE
cpu占用问题

### ISSUE THREAD

**Issue by tush3n-bese** [2lifetop/Pal-Server-Install#17]
![image](https://github.com/2lifetop/Pal-Server-Install/assets/117173053/7f0bed3a-e7ad-4e53-a089-ebb982172bd7)
这个cpu占用是否正常

**Comment by 2lifetop** [comment]
正常，服务端一般占用会在100%到400%之间。也就是占用1到4个核心的资源。在这个范围内都是正常的。
