### ISSUE TITLE
修改服务器配置无法生效

### ISSUE THREAD

**Issue by Creepi** [2lifetop/Pal-Server-Install#2]
操作步骤
1.）wget -O PalWorldSettings.ini https://www.xuehaiwu.com/Pal/configs/config_1706158875.txt
2.）./PalServerInstall.sh, 4 修改服务端配置
3）./PalServerInstall.sh, 7 重启服务端

**Comment by LittleFi987** [comment]
+1 我也无法生效

**Comment by 2lifetop** [comment]
运行：
```
docker cp steamcmd:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini  log.txt
cat log.txt
```
将结果对比一下你修改的内容再看看即可。如空白请重新尝试。如果已经是修改后的可以再次尝试重启服务端，等待两分钟

**Comment by Creepi** [comment]
> 运行：
> 
> ```
> docker cp steamcmd:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini  log.txt
> cat log.txt
> ```
> 
> 将结果对比一下你修改的内容再看看即可。如空白请重新尝试。如果已经是修改后的可以再次尝试重启服务端，等待两分钟

确实是我修改后的内容，但是仍然无法生效，是否和我调整的内容有关，我调整了服务器名以及管理员和普通用户密码

**Comment by LittleFi987** [comment]
> 运行：
> 
> ```
> docker cp steamcmd:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini  log.txt
> cat log.txt
> ```
> 
> 将结果对比一下你修改的内容再看看即可。如空白请重新尝试。如果已经是修改后的可以再次尝试重启服务端，等待两分钟

都不行，我看了容器里的配置文件，确实是我修改过后的

**Comment by jiangchenyu** [comment]
最新脚本还是无法生效

**Comment by LittleFi987** [comment]
修改完配置后，需要把存档导出，再导入，重启才能生效

**Comment by jethu256** [comment]
> 修改完配置后，需要把存档导出，再导入，重启才能生效

1、安装幻兽帕鲁服务端
2、启动幻兽帕鲁服务端
3、停止幻兽帕鲁服务端
4、修改服务端配置
5、增加swap内存
6、删除swap内存
7、增加定时重启
8、重启幻兽帕鲁服务端
9、查看幻兽帕鲁服务端状态
10、更新幻兽帕鲁服务端
11、删除幻兽帕鲁服务端
12、更新补丁版本
13、导入幻兽帕鲁存档及配置
14、导出幻兽帕鲁存档及配置
15、退出脚本
你好 请问是按14 然后13 再8 吗？ 我这么操作还是不生效呢 但是查看PalWorldSettings.ini 确实是修改后的配置

**Comment by LittleFi987** [comment]
> > 修改完配置后，需要把存档导出，再导入，重启才能生效
> 
> 1、安装幻兽帕鲁服务端 2、启动幻兽帕鲁服务端 3、停止幻兽帕鲁服务端 4、修改服务端配置 5、增加swap内存 6、删除swap内存 7、增加定时重启 8、重启幻兽帕鲁服务端 9、查看幻兽帕鲁服务端状态 10、更新幻兽帕鲁服务端 11、删除幻兽帕鲁服务端 12、更新补丁版本 13、导入幻兽帕鲁存档及配置 14、导出幻兽帕鲁存档及配置 15、退出脚本 你好 请问是按14 然后13 再8 吗？ 我这么操作还是不生效呢 但是查看PalWorldSettings.ini 确实是修改后的配置

在哪查看的配置呢？需要检查下容器里的配置是不是你修改后的配置

**Comment by jethu256** [comment]
> > > 修改完配置后，需要把存档导出，再导入，重启才能生效
> > 
> > 
> > 1、安装幻兽帕鲁服务端 2、启动幻兽帕鲁服务端 3、停止幻兽帕鲁服务端 4、修改服务端配置 5、增加swap内存 6、删除swap内存 7、增加定时重启 8、重启幻兽帕鲁服务端 9、查看幻兽帕鲁服务端状态 10、更新幻兽帕鲁服务端 11、删除幻兽帕鲁服务端 12、更新补丁版本 13、导入幻兽帕鲁存档及配置 14、导出幻兽帕鲁存档及配置 15、退出脚本 你好 请问是按14 然后13 再8 吗？ 我这么操作还是不生效呢 但是查看PalWorldSettings.ini 确实是修改后的配置
> 
> 在哪查看的配置呢？需要检查下容器里的配置是不是你修改后的配置

docker exec -it steamcmd bash
more ./Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
看的这个 确实是修改后的配置文件了 我改了端口也没生效

**Comment by LittleFi987** [comment]
> > > > 修改完配置后，需要把存档导出，再导入，重启才能生效
> > > 
> > > 
> > > 1、安装幻兽帕鲁服务端 2、启动幻兽帕鲁服务端 3、停止幻兽帕鲁服务端 4、修改服务端配置 5、增加swap内存 6、删除swap内存 7、增加定时重启 8、重启幻兽帕鲁服务端 9、查看幻兽帕鲁服务端状态 10、更新幻兽帕鲁服务端 11、删除幻兽帕鲁服务端 12、更新补丁版本 13、导入幻兽帕鲁存档及配置 14、导出幻兽帕鲁存档及配置 15、退出脚本 你好 请问是按14 然后13 再8 吗？ 我这么操作还是不生效呢 但是查看PalWorldSettings.ini 确实是修改后的配置
> > 
> > 
> > 在哪查看的配置呢？需要检查下容器里的配置是不是你修改后的配置
> 
> docker exec -it steamcmd bash more ./Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini 看的这个 确实是修改后的配置文件了 我改了端口也没生效

停止服务
导出存档
修改配置
导入存档
启动服务

再试试

**Comment by jethu256** [comment]
> > > > > 修改完配置后，需要把存档导出，再导入，重启才能生效
> > > > 
> > > > 
> > > > 1、安装幻兽帕鲁服务端 2、启动幻兽帕鲁服务端 3、停止幻兽帕鲁服务端 4、修改服务端配置 5、增加swap内存 6、删除swap内存 7、增加定时重启 8、重启幻兽帕鲁服务端 9、查看幻兽帕鲁服务端状态 10、更新幻兽帕鲁服务端 11、删除幻兽帕鲁服务端 12、更新补丁版本 13、导入幻兽帕鲁存档及配置 14、导出幻兽帕鲁存档及配置 15、退出脚本 你好 请问是按14 然后13 再8 吗？ 我这么操作还是不生效呢 但是查看PalWorldSettings.ini 确实是修改后的配置
> > > 
> > > 
> > > 在哪查看的配置呢？需要检查下容器里的配置是不是你修改后的配置
> > 
> > 
> > docker exec -it steamcmd bash more ./Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini 看的这个 确实是修改后的配置文件了 我改了端口也没生效
> 
> 停止服务 导出存档 修改配置 导入存档 启动服务
> 
> 再试试

谢谢，但是我这里导出的时候 ./Saved/Config/LinuxServer/PalWorldSettings.ini  这个文件是空的 我奇怪 你的会吗？
https://www.xuehaiwu.com/Pal/configs/config_1701519827.txt 然后我用这个覆盖后再导入也不行

**Comment by 2lifetop** [comment]
> > > > > > 修改完配置后，需要把存档导出，再导入，重启才能生效
> > > > > 
> > > > > 
> > > > > 1、安装幻兽帕鲁服务端 2、启动幻兽帕鲁服务端 3、停止幻兽帕鲁服务端 4、修改服务端配置 5、增加swap内存 6、删除swap内存 7、增加定时重启 8、重启幻兽帕鲁服务端 9、查看幻兽帕鲁服务端状态 10、更新幻兽帕鲁服务端 11、删除幻兽帕鲁服务端 12、更新补丁版本 13、导入幻兽帕鲁存档及配置 14、导出幻兽帕鲁存档及配置 15、退出脚本 你好 请问是按14 然后13 再8 吗？ 我这么操作还是不生效呢 但是查看PalWorldSettings.ini 确实是修改后的配置
> > > > 
> > > > 
> > > > 在哪查看的配置呢？需要检查下容器里的配置是不是你修改后的配置
> > > 
> > > 
> > > docker exec -it steamcmd bash more ./Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini 看的这个 确实是修改后的配置文件了 我改了端口也没生效
> > 
> > 
> > 停止服务 导出存档 修改配置 导入存档 启动服务
> > 再试试
> 
> 谢谢，但是我这里导出的时候 ./Saved/Config/LinuxServer/PalWorldSettings.ini 这个文件是空的 我奇怪 你的会吗？ https://www.xuehaiwu.com/Pal/configs/config_1701519827.txt 然后我用这个覆盖后再导入也不行

晚点脚本更新，大部分用户选择4选项修改配置后，服务端配置就会被正确修改。如果不行导入导出之后也可以。晚点更新修改配置的逻辑，增加一个权限操作。这样就可以避免修改配置之后服务端因为权限不足导致仍旧使用默认配置运行。

**Comment by jethu256** [comment]
> > > > > > > 修改完配置后，需要把存档导出，再导入，重启才能生效
> > > > > > 
> > > > > > 
> > > > > > 1、安装幻兽帕鲁服务端 2、启动幻兽帕鲁服务端 3、停止幻兽帕鲁服务端 4、修改服务端配置 5、增加swap内存 6、删除swap内存 7、增加定时重启 8、重启幻兽帕鲁服务端 9、查看幻兽帕鲁服务端状态 10、更新幻兽帕鲁服务端 11、删除幻兽帕鲁服务端 12、更新补丁版本 13、导入幻兽帕鲁存档及配置 14、导出幻兽帕鲁存档及配置 15、退出脚本 你好 请问是按14 然后13 再8 吗？ 我这么操作还是不生效呢 但是查看PalWorldSettings.ini 确实是修改后的配置
> > > > > 
> > > > > 
> > > > > 在哪查看的配置呢？需要检查下容器里的配置是不是你修改后的配置
> > > > 
> > > > 
> > > > docker exec -it steamcmd bash more ./Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini 看的这个 确实是修改后的配置文件了 我改了端口也没生效
> > > 
> > > 
> > > 停止服务 导出存档 修改配置 导入存档 启动服务
> > > 再试试
> > 
> > 
> > 谢谢，但是我这里导出的时候 ./Saved/Config/LinuxServer/PalWorldSettings.ini 这个文件是空的 我奇怪 你的会吗？ https://www.xuehaiwu.com/Pal/configs/config_1701519827.txt 然后我用这个覆盖后再导入也不行
> 
> 晚点脚本更新，大部分用户选择4选项修改配置后，服务端配置就会被正确修改。如果不行导入导出之后也可以。晚点更新修改配置的逻辑，增加一个权限操作。这样就可以避免修改配置之后服务端因为权限不足导致仍旧使用默认配置运行。

👍那晚点我再试试 多谢 我服务器环境是ubuntu 22.04  为什么第一次导出的时候 docker cp steamcmd:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini  log.txt
cat log.txt是空文件呢？

**Comment by 2lifetop** [comment]
> ，大部分用户选择4选项修改配置后，服务端配置就会被正确修改。如果不行导入导出之后也可以。晚点更新修改配置的逻辑，增加一个权限操作。这样就可以避免修改配置之后服务端因为权限不足导致仍旧使用默认配置运行。

因为默认状态下这个就是空的，你只有成功执行4操作之后才能看到该文件的内容。

**Comment by jethu256** [comment]
> > ，大部分用户选择4选项修改配置后，服务端配置就会被正确修改。如果不行导入导出之后也可以。晚点更新修改配置的逻辑，增加一个权限操作。这样就可以避免修改配置之后服务端因为权限不足导致仍旧使用默认配置运行。
> 
> 因为默认状态下这个就是空的，你只有成功执行4操作之后才能看到该文件的内容。

用了更新后脚本重新安装一遍 生成配置后 按4修改服务端配置  然后启动服务端 配置还是不生效
docker cp steamcmd:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini  log.txt
cat log.txt  看这个看配置确实是修改过的  我把端口8211 改成8811 不起作用 服务起来后监听的还是8211 
我的环境是Ubuntu 22.04.3 LTS
