### ISSUE TITLE
关于Docker的重启与备份可能的冲突

### ISSUE THREAD

**Issue by Shay7sev** [2lifetop/Pal-Server-Install#24]
首先感谢作者的脚本，很好用～

我有一个疑问，如果备份任务在容器重启的过程中开始运行，那么备份可能会失败，因为在重启过程中容器可能暂时不可用。我发现作者设置的备份时间默认是5点重启时间也是默认5点，Cron并不会等待第一个任务完成后再启动第二个任务，这取决于操作系统如何调度进程。所以是不是可以把默认备份时间调成4.30，这样其他用作者脚本的小伙伴使用脚本中默认的的备份和重启应该就不会遇到备份失败的问题了

**Comment by 2lifetop** [comment]
好的，感谢建议
