### ISSUE TITLE
提供两个脚本可以写到里面 【容器备份】【容器恢复】

### ISSUE THREAD

**Issue by nodesire7** [2lifetop/Pal-Server-Install#6]
【容器备份】
[serverbackup.zip](https://github.com/2lifetop/Pal-Server-Install/files/14053729/serverbackup.zip)

【容器恢复】
[restore.zip](https://github.com/2lifetop/Pal-Server-Install/files/14053725/restore.zip)

里面文件夹地址需要修改 容器如果名称不是steamcmd需要修改
可以设置成定时任务 定时备份

**Comment by nodesire7** [comment]
同时我有个问题，我的docker容器pal占用非常高，但是cpu总占用一直在20%~30%。有办法解决吗

**Comment by 2lifetop** [comment]
感谢提供思路，Pal由于官方服务端设计问题，导致会持续占用内存需要按需器释放内存才行。目前没有很好地解决方案，CPU占用基本上不会受影响，90%的情况都是内存爆了导致的
