### ISSUE TITLE
客户端

### ISSUE THREAD

**Issue by chaos-zhu** [2lifetop/Pal-Server-Install#8]
话说有大佬能贴个对应版本的客户端下载地址不，昨天部署完，打开帕鲁连接提示版本不一致，无法连接

**Comment by 56warmers** [comment]
> 话说有大佬能贴个对应版本的客户端下载地址不，昨天部署完，打开帕鲁连接提示版本不一致，无法连接

昨天客户端更新了，进不去正常。
正版随时更新服务端应该就没问题了。
开心版只能去论坛找，自己升级客户端版本吧。
看steam社区开发者意思是后续小修小补会越来越频繁

**Comment by 2lifetop** [comment]
特定客户端只能靠自己找了，这个没办法。同理服务端也是。
